### PR TITLE
Fix #23 by adding support for a custom "parent iframe" config value

### LINKED ISSUE #23: Running a parent-child iframe configuration inside another iframe does not work
This is a crazy edge-use-case, but still a valid technical question, I guess.

So, I have a working setup using two html-files - one for the parent.html and one for the iframed child iframed.html, using the iframeApi, and it is working as it should.

Now, however, I wish to put one or more of these "parent.html" into a big html file. 
The use case is, that is the "parent.html" is a working "widget" type of application, and I want to show off multiple different versions of "parent.html" with different configurations.

So - I want an embeds multiple iframes of the "parent.html" but this does not work, because the "iframe-api.js" checks to see if itself is iframed, and if so thinks it is the "child iframe" and thus waits for a "parent document" to present itself.

The main culprit is this simple function

```
function isIframed() {
  return parent !== window;
}
```

Adding a simple custom override check fixes my problem, because I can specify a global variable in the actual "parent.html", such as `window.iFrameApiParent=true;`

```
function isIframed() {
  return parent !== window && !window.iFrameApiParent;
}
```

### PR DESCRIPTION
**Pull request by dagjomar**

### CODE REVIEW

**Comment by bahmutov** [comment]
I will merge this if you also add doc to the README, ok?

**Comment by dagjomar** [comment]
@bahmutov: I updated README now. See if it is as you want it.

**Comment by bahmutov** [comment]
nice, thank you!

**Comment by bahmutov** [comment]
published under 0.10.0

**Pull request merged**
